import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// 翻译字典 - 完整版
const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Navbar
    'nav.brand': 'Bot管理',
    'nav.chat': '双向聊天',
    'nav.chat.short': '双向',
    'nav.keyboard': '菜单键盘',
    'nav.keyboard.short': '键盘',
    'nav.store': '自助商城',
    'nav.store.short': '商城',
    'nav.userCenter': '用户中心',
    'nav.logout': '退出',
    'nav.register': '注册',
    'nav.login': '登录',
    
    // Store Page
    'store.title': '自助商城',
    'store.auto': '自动充值',
    'store.card': '卡密购买',
    'store.selectProduct': '请选择商品',
    'store.selectPayment': '请选择支付方式',
    'store.stock': '库存',
    'store.soldOut': '已售罄',
    'store.days': '天',
    'store.buy': '购买',
    'store.enterBotId': '请输入账号ID',
    'store.enterContact': '请输入邮箱或手机号',
    'store.payment': '支付方式',
    'store.payNow': '立即支付',
    'store.orderQuery': '订单查询',
    'store.paySuccess': '支付成功',
    'store.expired': '已过期',
    'store.confirmPayment': '确认支付',
    'store.payAmount': '请支付精确金额',
    'store.scanToPay': '扫码支付',
    'store.wechatScan': '请使用微信扫码支付',
    'store.alipayScan': '请使用支付宝扫码支付',
    'store.openAlipay': '手机用户点击打开支付宝',
    'store.paidDone': '我已完成支付',
    'store.orderComplete': '订单完成',
    'store.cardInfo': '卡密信息',
    'store.copy': '复制',
    'store.copySuccess': '复制成功',
    'store.loadingCard': '正在安全从云端获取卡密，请稍候...',
    'store.retry': '重试',
    'store.noStock': '库存不足，暂时无法购买',
    'store.createOrderFailed': '创建订单失败，请稍后重试',
    'store.getPayLinkFailed': '获取支付链接失败，请稍后重试',
    'store.chat': '双向聊天',
    'store.keyboardMenu': '菜单键盘',
    'store.tgMall': 'TG商城',
    
    // Auth
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.submit': '提交',
    'auth.welcomeBack': '欢迎回来',
    'auth.createAccount': '创建账户',
    'auth.loginDesc': '请登录您的账户',
    'auth.registerDesc': '请填写以下信息注册',
    'auth.noAccount': '没有账户？',
    'auth.hasAccount': '已有账户？',
    'auth.forgotPassword': '忘记密码？',
    
    // User Center
    'user.center': '用户中心',
    'user.profile': '个人资料',
    'user.settings': '设置',
    'user.bots': '我的机器人',
    'user.orders': '我的订单',
    'user.balance': '余额',
    'user.recharge': '充值',
    
    // Keyboard Menu
    'keyboard.title': '菜单键盘',
    'keyboard.connect': '连接机器人',
    'keyboard.disconnect': '断开连接',
    'keyboard.connected': '已连接',
    'keyboard.notConnected': '未连接',
    'keyboard.botToken': '机器人令牌',
    'keyboard.userId': '用户ID',
    'keyboard.settings': '设置',
    'keyboard.commands': '命令管理',
    'keyboard.menu': '菜单配置',
    'keyboard.autoReply': '自动回复',
    'keyboard.flowMessage': '消息流程',
    'keyboard.users': '用户管理',
    'keyboard.shop': 'TG商城',
    'keyboard.guide': '配置指南',
    'keyboard.message': '消息推送',
    'keyboard.messageEditor': '消息编辑器',
    'keyboard.addMessage': '添加消息',
    'keyboard.deleteMessage': '删除消息',
    'keyboard.messageType': '消息类型',
    'keyboard.text': '文本',
    'keyboard.photo': '图片',
    'keyboard.video': '视频',
    'keyboard.content': '内容',
    'keyboard.mediaUrl': '媒体链接',
    'keyboard.inlineKeyboard': '内联键盘',
    'keyboard.addButton': '添加按钮',
    'keyboard.addRow': '添加行',
    'keyboard.buttonText': '按钮文字',
    'keyboard.buttonType': '按钮类型',
    'keyboard.buttonValue': '按钮值',
    'keyboard.url': '链接',
    'keyboard.callback': '回调',
    'keyboard.webApp': 'Web应用',
    'keyboard.preview': '预览',
    'keyboard.send': '发送',
    'keyboard.save': '保存',
    'keyboard.syncToCloud': '同步到云端',
    'keyboard.loadFromCloud': '从云端加载',
    'keyboard.export': '导出',
    'keyboard.import': '导入',
    'keyboard.addCommand': '添加命令',
    'keyboard.commandName': '命令名称',
    'keyboard.commandDesc': '命令描述',
    'keyboard.addMenuPage': '添加菜单页',
    'keyboard.pageName': '页面名称',
    'keyboard.addMenuRow': '添加菜单行',
    'keyboard.buttonAction': '按钮动作',
    'keyboard.navigate': '跳转页面',
    'keyboard.sendText': '发送文本',
    'keyboard.targetPage': '目标页面',
    'keyboard.mainMenu': '主菜单',
    'keyboard.subMenu': '子菜单',
    'keyboard.back': '返回上级',
    'keyboard.addRule': '添加规则',
    'keyboard.triggerType': '触发类型',
    'keyboard.keyword': '关键词',
    'keyboard.command': '命令',
    'keyboard.triggerValue': '触发值',
    'keyboard.replyMessages': '回复消息',
    'keyboard.disablePreview': '禁用链接预览',
    'keyboard.proxyMode': '代理模式',
    'keyboard.enableProxy': '启用代理',
    'keyboard.webhookStatus': 'Webhook状态',
    'keyboard.webhookActive': 'Webhook已激活',
    'keyboard.webhookInactive': 'Webhook未激活',
    'keyboard.refreshWebhook': '刷新Webhook',
    'keyboard.setWebhook': '设置Webhook',
    'keyboard.deleteWebhook': '删除Webhook',
    'keyboard.botInfo': '机器人信息',
    'keyboard.botName': '机器人名称',
    'keyboard.botUsername': '机器人用户名',
    'keyboard.targetChat': '目标会话',
    'keyboard.chatId': '会话ID',
    'keyboard.selectUser': '选择用户',
    'keyboard.userList': '用户列表',
    'keyboard.noUsers': '暂无用户',
    'keyboard.lastSeen': '最后活跃',
    'keyboard.joined': '加入时间',
    'keyboard.total': '共',
    'keyboard.users.count': '个用户',
    'keyboard.bilingualButton': '双语按钮',
    'keyboard.enableBilingual': '启用双语按钮',
    'keyboard.englishText': '英文文字',
    'keyboard.forceMenuOnStart': '强制显示菜单',
    'keyboard.activityLog': '活动日志',
    'keyboard.enableActivityLog': '启用活动日志',
    'keyboard.autoCleanup': '自动清理',
    'keyboard.enableAutoCleanup': '启用自动清理',
    'keyboard.cleanupDays': '清理天数',
    'keyboard.adminChatId': '管理员会话ID',
    
    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.confirm': '确认',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.add': '添加',
    'common.search': '搜索',
    'common.noData': '暂无数据',
    'common.copy': '复制',
    'common.copied': '已复制',
    'common.refresh': '刷新',
    'common.close': '关闭',
    'common.submit': '提交',
    'common.reset': '重置',
    'common.clear': '清空',
    'common.select': '选择',
    'common.upload': '上传',
    'common.download': '下载',
    'common.preview': '预览',
    'common.test': '测试',
    'common.enable': '启用',
    'common.disable': '禁用',
    'common.enabled': '已启用',
    'common.disabled': '已禁用',
    'common.status': '状态',
    'common.actions': '操作',
    'common.name': '名称',
    'common.description': '描述',
    'common.price': '价格',
    'common.quantity': '数量',
    'common.total': '总计',
    'common.date': '日期',
    'common.time': '时间',
    'common.type': '类型',
    'common.category': '分类',
    'common.all': '全部',
    'common.none': '无',
    'common.yes': '是',
    'common.no': '否',
    'common.or': '或',
    'common.and': '和',
    'common.required': '必填',
    'common.optional': '可选',
    'common.example': '例如',
    'common.tips': '提示',
    'common.warning': '警告',
    'common.info': '信息',
    'common.version': '版本',
    
    // Gateway Config
    'gateway.title': '网关设置',
    'gateway.blockchain': '区块链监听',
    'gateway.receiveAddress': '收款地址',
    'gateway.tronGridKey': 'TronGrid Key',
    'gateway.hupi': '虎皮椒接口',
    'gateway.wechat': '微信',
    'gateway.alipay': '支付宝',
    'gateway.appId': 'App ID',
    'gateway.secret': 'Secret',
    'gateway.antiCollision': '防撞单算法',
    'gateway.antiCollisionDesc': '自动生成毫级随机尾数',
    'gateway.saveAll': '保存所有配置',
    
    // Product Management
    'product.title': '商品管理',
    'product.add': '添加商品',
    'product.edit': '编辑商品',
    'product.name': '商品名称',
    'product.price': '价格',
    'product.priceCny': '人民币价格',
    'product.priceUsdt': 'USDT价格',
    'product.priceTrx': 'TRX价格',
    'product.stock': '库存',
    'product.duration': '时长',
    'product.active': '上架',
    'product.inactive': '下架',
    'product.tags': '标签',
    'product.refreshRates': '刷新汇率',
    'product.currentRate': '当前汇率',
    
    // Order
    'order.title': '订单管理',
    'order.no': '订单号',
    'order.status': '订单状态',
    'order.pending': '待支付',
    'order.paid': '已支付',
    'order.completed': '已完成',
    'order.cancelled': '已取消',
    'order.expired': '已过期',
    'order.amount': '订单金额',
    'order.payMethod': '支付方式',
    'order.createTime': '创建时间',
    'order.payTime': '支付时间',
    'order.deliverTime': '发货时间',
    
    // TG Shop
    'tgshop.title': 'TG商城',
    'tgshop.products': '商品管理',
    'tgshop.orders': '订单管理',
    'tgshop.categories': '分类管理',
    'tgshop.settings': '商城设置',
    'tgshop.welcome': '欢迎语',
    'tgshop.payment': '支付设置',
    'tgshop.delivery': '发货设置',
  },
  en: {
    // Navbar
    'nav.brand': 'Bot Manager',
    'nav.chat': 'Two-way Chat',
    'nav.chat.short': 'Chat',
    'nav.keyboard': 'Menu Keyboard',
    'nav.keyboard.short': 'Menu',
    'nav.store': 'Store',
    'nav.store.short': 'Store',
    'nav.userCenter': 'Account',
    'nav.logout': 'Logout',
    'nav.register': 'Sign Up',
    'nav.login': 'Login',
    
    // Store Page
    'store.title': 'Self-service Store',
    'store.auto': 'Auto Recharge',
    'store.card': 'Card Key',
    'store.selectProduct': 'Select a product',
    'store.selectPayment': 'Select payment method',
    'store.stock': 'Stock',
    'store.soldOut': 'Sold Out',
    'store.days': 'days',
    'store.buy': 'Buy',
    'store.enterBotId': 'Enter your account ID',
    'store.enterContact': 'Enter email or phone',
    'store.payment': 'Payment',
    'store.payNow': 'Pay Now',
    'store.orderQuery': 'Order Query',
    'store.paySuccess': 'Payment Success',
    'store.expired': 'Expired',
    'store.confirmPayment': 'Confirm Payment',
    'store.payAmount': 'Please pay exact amount',
    'store.scanToPay': 'Scan to Pay',
    'store.wechatScan': 'Scan with WeChat to pay',
    'store.alipayScan': 'Scan with Alipay to pay',
    'store.openAlipay': 'Tap to open Alipay',
    'store.paidDone': 'I have paid',
    'store.orderComplete': 'Order Complete',
    'store.cardInfo': 'Card Key',
    'store.copy': 'Copy',
    'store.copySuccess': 'Copied',
    'store.loadingCard': 'Fetching card key securely...',
    'store.retry': 'Retry',
    'store.noStock': 'Out of stock',
    'store.createOrderFailed': 'Failed to create order, please try again',
    'store.getPayLinkFailed': 'Failed to get payment link, please try again',
    'store.chat': 'Two-way Chat',
    'store.keyboardMenu': 'Menu Keyboard',
    'store.tgMall': 'TG Store',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.submit': 'Submit',
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.loginDesc': 'Please login to your account',
    'auth.registerDesc': 'Please fill in the information to register',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.forgotPassword': 'Forgot password?',
    
    // User Center
    'user.center': 'User Center',
    'user.profile': 'Profile',
    'user.settings': 'Settings',
    'user.bots': 'My Bots',
    'user.orders': 'My Orders',
    'user.balance': 'Balance',
    'user.recharge': 'Recharge',
    
    // Keyboard Menu
    'keyboard.title': 'Menu Keyboard',
    'keyboard.connect': 'Connect Bot',
    'keyboard.disconnect': 'Disconnect',
    'keyboard.connected': 'Connected',
    'keyboard.notConnected': 'Not Connected',
    'keyboard.botToken': 'Bot Token',
    'keyboard.userId': 'User ID',
    'keyboard.settings': 'Settings',
    'keyboard.commands': 'Commands',
    'keyboard.menu': 'Menu Config',
    'keyboard.autoReply': 'Auto Reply',
    'keyboard.flowMessage': 'Flow Messages',
    'keyboard.users': 'User Management',
    'keyboard.shop': 'TG Shop',
    'keyboard.guide': 'Config Guide',
    'keyboard.message': 'Message Push',
    'keyboard.messageEditor': 'Message Editor',
    'keyboard.addMessage': 'Add Message',
    'keyboard.deleteMessage': 'Delete Message',
    'keyboard.messageType': 'Message Type',
    'keyboard.text': 'Text',
    'keyboard.photo': 'Photo',
    'keyboard.video': 'Video',
    'keyboard.content': 'Content',
    'keyboard.mediaUrl': 'Media URL',
    'keyboard.inlineKeyboard': 'Inline Keyboard',
    'keyboard.addButton': 'Add Button',
    'keyboard.addRow': 'Add Row',
    'keyboard.buttonText': 'Button Text',
    'keyboard.buttonType': 'Button Type',
    'keyboard.buttonValue': 'Button Value',
    'keyboard.url': 'URL',
    'keyboard.callback': 'Callback',
    'keyboard.webApp': 'Web App',
    'keyboard.preview': 'Preview',
    'keyboard.send': 'Send',
    'keyboard.save': 'Save',
    'keyboard.syncToCloud': 'Sync to Cloud',
    'keyboard.loadFromCloud': 'Load from Cloud',
    'keyboard.export': 'Export',
    'keyboard.import': 'Import',
    'keyboard.addCommand': 'Add Command',
    'keyboard.commandName': 'Command Name',
    'keyboard.commandDesc': 'Command Description',
    'keyboard.addMenuPage': 'Add Menu Page',
    'keyboard.pageName': 'Page Name',
    'keyboard.addMenuRow': 'Add Menu Row',
    'keyboard.buttonAction': 'Button Action',
    'keyboard.navigate': 'Navigate',
    'keyboard.sendText': 'Send Text',
    'keyboard.targetPage': 'Target Page',
    'keyboard.mainMenu': 'Main Menu',
    'keyboard.subMenu': 'Sub Menu',
    'keyboard.back': 'Back',
    'keyboard.addRule': 'Add Rule',
    'keyboard.triggerType': 'Trigger Type',
    'keyboard.keyword': 'Keyword',
    'keyboard.command': 'Command',
    'keyboard.triggerValue': 'Trigger Value',
    'keyboard.replyMessages': 'Reply Messages',
    'keyboard.disablePreview': 'Disable Link Preview',
    'keyboard.proxyMode': 'Proxy Mode',
    'keyboard.enableProxy': 'Enable Proxy',
    'keyboard.webhookStatus': 'Webhook Status',
    'keyboard.webhookActive': 'Webhook Active',
    'keyboard.webhookInactive': 'Webhook Inactive',
    'keyboard.refreshWebhook': 'Refresh Webhook',
    'keyboard.setWebhook': 'Set Webhook',
    'keyboard.deleteWebhook': 'Delete Webhook',
    'keyboard.botInfo': 'Bot Info',
    'keyboard.botName': 'Bot Name',
    'keyboard.botUsername': 'Bot Username',
    'keyboard.targetChat': 'Target Chat',
    'keyboard.chatId': 'Chat ID',
    'keyboard.selectUser': 'Select User',
    'keyboard.userList': 'User List',
    'keyboard.noUsers': 'No users',
    'keyboard.lastSeen': 'Last seen',
    'keyboard.joined': 'Joined',
    'keyboard.total': 'Total',
    'keyboard.users.count': 'users',
    'keyboard.bilingualButton': 'Bilingual Button',
    'keyboard.enableBilingual': 'Enable Bilingual Buttons',
    'keyboard.englishText': 'English Text',
    'keyboard.forceMenuOnStart': 'Force Menu on Start',
    'keyboard.activityLog': 'Activity Log',
    'keyboard.enableActivityLog': 'Enable Activity Log',
    'keyboard.autoCleanup': 'Auto Cleanup',
    'keyboard.enableAutoCleanup': 'Enable Auto Cleanup',
    'keyboard.cleanupDays': 'Cleanup Days',
    'keyboard.adminChatId': 'Admin Chat ID',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.noData': 'No data',
    'common.copy': 'Copy',
    'common.copied': 'Copied',
    'common.refresh': 'Refresh',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.select': 'Select',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.preview': 'Preview',
    'common.test': 'Test',
    'common.enable': 'Enable',
    'common.disable': 'Disable',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.type': 'Type',
    'common.category': 'Category',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.or': 'or',
    'common.and': 'and',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.example': 'e.g.',
    'common.tips': 'Tips',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.version': 'Version',
    
    // Gateway Config
    'gateway.title': 'Gateway Settings',
    'gateway.blockchain': 'Blockchain Monitor',
    'gateway.receiveAddress': 'Receive Address',
    'gateway.tronGridKey': 'TronGrid Key',
    'gateway.hupi': 'Hupi Payment',
    'gateway.wechat': 'WeChat',
    'gateway.alipay': 'Alipay',
    'gateway.appId': 'App ID',
    'gateway.secret': 'Secret',
    'gateway.antiCollision': 'Anti-Collision Algorithm',
    'gateway.antiCollisionDesc': 'Auto generate random decimals',
    'gateway.saveAll': 'Save All Settings',
    
    // Product Management
    'product.title': 'Product Management',
    'product.add': 'Add Product',
    'product.edit': 'Edit Product',
    'product.name': 'Product Name',
    'product.price': 'Price',
    'product.priceCny': 'CNY Price',
    'product.priceUsdt': 'USDT Price',
    'product.priceTrx': 'TRX Price',
    'product.stock': 'Stock',
    'product.duration': 'Duration',
    'product.active': 'Active',
    'product.inactive': 'Inactive',
    'product.tags': 'Tags',
    'product.refreshRates': 'Refresh Rates',
    'product.currentRate': 'Current Rate',
    
    // Order
    'order.title': 'Order Management',
    'order.no': 'Order No.',
    'order.status': 'Order Status',
    'order.pending': 'Pending',
    'order.paid': 'Paid',
    'order.completed': 'Completed',
    'order.cancelled': 'Cancelled',
    'order.expired': 'Expired',
    'order.amount': 'Amount',
    'order.payMethod': 'Payment Method',
    'order.createTime': 'Created At',
    'order.payTime': 'Paid At',
    'order.deliverTime': 'Delivered At',
    
    // TG Shop
    'tgshop.title': 'TG Shop',
    'tgshop.products': 'Products',
    'tgshop.orders': 'Orders',
    'tgshop.categories': 'Categories',
    'tgshop.settings': 'Shop Settings',
    'tgshop.welcome': 'Welcome Message',
    'tgshop.payment': 'Payment Settings',
    'tgshop.delivery': 'Delivery Settings',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved === 'en' ? 'en' : 'zh') as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default useLanguage;
