import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// 完整翻译字典
const translations: Record<Language, Record<string, string>> = {
  zh: {
    // Navbar
    'nav.brand': 'Bot管理',
    'nav.chat': '双向聊天',
    'nav.chat.short': '双向',
    'nav.keyboard': '菜单键盘',
    'nav.keyboard.short': '键盘',
    'nav.store': '自助商城',
    'nav.store.short': '商城',
    'nav.userCenter': '用户中心',
    'nav.logout': '退出',
    'nav.register': '注册',
    'nav.login': '登录',
    
    // Store Page
    'store.title': '自助商城',
    'store.auto': '自动充值',
    'store.card': '卡密购买',
    'store.selectProduct': '请选择商品',
    'store.selectPayment': '请选择支付方式',
    'store.stock': '库存',
    'store.soldOut': '已售罄',
    'store.days': '天',
    'store.buy': '购买',
    'store.enterBotId': '请输入账号ID',
    'store.enterContact': '请输入邮箱或手机号',
    'store.payment': '支付方式',
    'store.payNow': '立即支付',
    'store.orderQuery': '订单查询',
    'store.paySuccess': '支付成功',
    'store.expired': '已过期',
    'store.confirmPayment': '确认支付',
    'store.payAmount': '请支付精确金额',
    'store.scanToPay': '扫码支付',
    'store.wechatScan': '请使用微信扫码支付',
    'store.alipayScan': '请使用支付宝扫码支付',
    'store.openAlipay': '手机用户点击打开支付宝',
    'store.paidDone': '我已完成支付',
    'store.orderComplete': '订单完成',
    'store.cardInfo': '卡密信息',
    'store.copy': '复制',
    'store.copySuccess': '复制成功',
    'store.copyFailed': '复制失败，请手动复制',
    'store.loadingCard': '正在安全从云端获取卡密，请稍候...',
    'store.retry': '重试',
    'store.noStock': '库存不足，暂时无法购买',
    'store.createOrderFailed': '创建订单失败，请稍后重试',
    'store.getPayLinkFailed': '获取支付链接失败，请稍后重试',
    'store.chat': '双向聊天',
    'store.keyboardMenu': '菜单键盘',
    'store.tgMall': 'TG商城',
    'store.connectedGateway': '已连接支付网关...',
    'store.paymentNetwork': '当前支付网络协议为 （TRX/TRC20）',
    'store.gettingPayLink': '正在获取支付链接...',
    'store.addressCopied': '地址已复制',
    'store.queryOrderHint': '请输入邮箱或手机号以查询订单！',
    'store.fillContactHint': '请填写邮箱或手机号，以便后续查询订单卡密！',
    'store.selectProductFirst': '请先选择商品',
    'store.selectPaymentMethod': '请选择支付方式',
    'store.enterAccountId': '请输入账号ID',
    'store.paymentNotDetected': '未检测到支付成功，请确保已完成支付后再试。如已支付请稍等片刻后重试。',
    'store.queryFailed': '查询订单状态失败，请稍后重试',
    'store.deliveryFailed': '发货失败，请点击重试或稍后在订单记录中查看',
    'store.cardSoldOut': '卡密已售罄，请联系客服',
    'store.systemError': '系统错误，请联系客服',
    'store.cannotGetProduct': '无法获取商品信息，请联系客服',
    'store.anonymous': '匿名',
    'store.none': '无',
    'store.orderHistory': '订单记录',
    'store.noOrders': '暂无订单记录',
    'store.pending': '待支付',
    'store.paid': '已支付',
    'store.activationSuccess': '已激活成功',
    'store.processing': '处理中...',
    'store.activationFailed': '激活失败',
    'store.contact': '联系方式',
    
    // Auth
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.submit': '提交',
    'auth.welcomeBack': '欢迎回来！',
    'auth.createAccount': '创建账户',
    'auth.loginDesc': '请登录您的账户',
    'auth.registerDesc': '请填写以下信息注册',
    'auth.noAccount': '没有账户？',
    'auth.hasAccount': '已有账户？',
    'auth.forgotPassword': '忘记密码？',
    'auth.loginSuccess': '登录成功',
    'auth.registerSuccess': '注册成功',
    'auth.autoLogin': '已自动登录，开始使用吧！',
    'auth.loginFailed': '登录失败',
    'auth.registerFailed': '注册失败',
    'auth.invalidCredentials': '邮箱或密码错误',
    'auth.emailRegistered': '此邮箱已被注册',
    'auth.passwordMin': '密码至少需要6位字符',
    'auth.fillEmailPassword': '请填写邮箱和密码',
    'auth.enterPassword': '输入密码',
    'auth.minChars': '至少6位字符',
    'auth.noRegisterTip': '无需注册也可在首页试用机器人功能',
    'auth.logging': '登录中...',
    'auth.registering': '注册中...',
    
    // User Center
    'user.center': '用户中心',
    'user.profile': '个人资料',
    'user.settings': '设置',
    'user.bots': '我的机器人',
    'user.orders': '我的订单',
    'user.balance': '余额',
    'user.recharge': '充值',
    'user.addBot': '添加机器人',
    'user.noBot': '暂无机器人',
    'user.addFirstBot': '点击上方按钮添加您的第一个机器人',
    'user.token': '令牌',
    'user.validity': '有效期',
    'user.forever': '永久',
    'user.expired': '已过期',
    'user.trial': '试用',
    'user.trialFull': '试用已满',
    'user.activated': '已激活',
    'user.trialing': '试用中',
    'user.renew': '续期',
    'user.serviceExpired': '服务已过期，请联系管理员续期',
    'user.trialUsedUp': '试用额度已用完，请绑定激活码',
    'user.bindCode': '绑定激活码',
    'user.renewActivate': '续期激活',
    'user.enterCode': '输入激活码...',
    'user.binding': '绑定中...',
    'user.bind': '绑定',
    'user.deleteSuccess': '删除成功',
    'user.botRemoved': '机器人已从列表中移除',
    'user.deleteFailed': '删除失败',
    'user.bindSuccess': '绑定成功',
    'user.codeBindSuccess': '激活码已成功绑定，机器人已激活',
    'user.bindFailed': '绑定失败',
    'user.addSuccess': '添加成功',
    'user.canTrial': '机器人已添加，可免费试用',
    'user.messages': '条消息',
    'user.loading': '正在加载...',
    'user.webPortClosed': 'Web端口已关闭',
    'user.enterCodeError': '请输入激活码',
    
    // Add Bot Dialog
    'bot.addTitle': '添加 Telegram 机器人',
    'bot.addDesc': '输入机器人信息即可开始试用，无需注册。免费试用20条消息。',
    'bot.token': '机器人令牌 (Bot Token)',
    'bot.tokenPlaceholder': '例如: 123456789:ABCdefGHIjklMNOpqrsTUVwxyz',
    'bot.tokenHint': '从 @BotFather 获取的机器人令牌，复制浏览器跳转 t.me/BotFather',
    'bot.userId': '您的 Telegram 用户ID',
    'bot.userIdPlaceholder': '例如: 123456789',
    'bot.userIdHint': '从 @userinfobot 获取复制ID，复制浏览器跳转 t.me/userinfobot',
    'bot.greeting': '欢迎语',
    'bot.greetingPlaceholder': '用户发送 /start 时的自动回复',
    'bot.greetingDefault': '你好！👋 有什么可以帮助你的吗？',
    'bot.startTrial': '开始试用',
    'bot.adding': '添加中...',
    'bot.addFailed': '添加失败',
    'bot.checkToken': '请检查令牌是否正确',
    'bot.fillRequired': '请填写机器人令牌和个人用户ID',
    
    // Keyboard Menu
    'keyboard.title': '菜单键盘',
    'keyboard.connect': '连接机器人',
    'keyboard.disconnect': '断开连接',
    'keyboard.connected': '已连接',
    'keyboard.notConnected': '未连接',
    'keyboard.botToken': '机器人令牌',
    'keyboard.userId': '用户ID',
    'keyboard.settings': '设置',
    'keyboard.commands': '命令管理',
    'keyboard.menu': '菜单配置',
    'keyboard.autoReply': '自动回复',
    'keyboard.flowMessage': '消息流程',
    'keyboard.users': '用户管理',
    'keyboard.shop': 'TG商城',
    'keyboard.guide': '配置指南',
    'keyboard.message': '消息推送',
    'keyboard.messageEditor': '消息编辑器',
    'keyboard.addMessage': '添加消息',
    'keyboard.deleteMessage': '删除消息',
    'keyboard.messageType': '消息类型',
    'keyboard.text': '文本',
    'keyboard.photo': '图片',
    'keyboard.video': '视频',
    'keyboard.content': '内容',
    'keyboard.mediaUrl': '媒体链接',
    'keyboard.inlineKeyboard': '内联键盘',
    'keyboard.addButton': '添加按钮',
    'keyboard.addRow': '添加行',
    'keyboard.buttonText': '按钮文字',
    'keyboard.buttonType': '按钮类型',
    'keyboard.buttonValue': '按钮值',
    'keyboard.url': '链接',
    'keyboard.callback': '回调',
    'keyboard.webApp': 'Web应用',
    'keyboard.preview': '预览',
    'keyboard.send': '发送',
    'keyboard.save': '保存',
    'keyboard.syncToCloud': '同步到云端',
    'keyboard.loadFromCloud': '从云端加载',
    'keyboard.export': '导出',
    'keyboard.import': '导入',
    'keyboard.addCommand': '添加命令',
    'keyboard.commandName': '命令名称',
    'keyboard.commandDesc': '命令描述',
    'keyboard.addMenuPage': '添加菜单页',
    'keyboard.pageName': '页面名称',
    'keyboard.addMenuRow': '添加菜单行',
    'keyboard.buttonAction': '按钮动作',
    'keyboard.navigate': '跳转页面',
    'keyboard.sendText': '发送文本',
    'keyboard.targetPage': '目标页面',
    'keyboard.mainMenu': '主菜单',
    'keyboard.subMenu': '子菜单',
    'keyboard.back': '返回上级',
    'keyboard.addRule': '添加规则',
    'keyboard.triggerType': '触发类型',
    'keyboard.keyword': '关键词',
    'keyboard.command': '命令',
    'keyboard.triggerValue': '触发值',
    'keyboard.replyMessages': '回复消息',
    'keyboard.disablePreview': '禁用链接预览',
    'keyboard.proxyMode': '代理模式',
    'keyboard.enableProxy': '启用代理',
    'keyboard.webhookStatus': 'Webhook状态',
    'keyboard.webhookActive': 'Webhook已激活',
    'keyboard.webhookInactive': 'Webhook未激活',
    'keyboard.refreshWebhook': '刷新Webhook',
    'keyboard.setWebhook': '设置Webhook',
    'keyboard.deleteWebhook': '删除Webhook',
    'keyboard.botInfo': '机器人信息',
    'keyboard.botName': '机器人名称',
    'keyboard.botUsername': '机器人用户名',
    'keyboard.targetChat': '目标会话',
    'keyboard.chatId': '会话ID',
    'keyboard.selectUser': '选择用户',
    'keyboard.userList': '用户列表',
    'keyboard.noUsers': '暂无用户',
    'keyboard.lastSeen': '最后活跃',
    'keyboard.joined': '加入时间',
    'keyboard.total': '共',
    'keyboard.users.count': '个用户',
    'keyboard.bilingualButton': '双语按钮',
    'keyboard.enableBilingual': '启用双语按钮',
    'keyboard.englishText': '英文文字',
    'keyboard.forceMenuOnStart': '强制显示菜单',
    'keyboard.activityLog': '活动日志',
    'keyboard.enableActivityLog': '启用活动日志',
    'keyboard.autoCleanup': '自动清理',
    'keyboard.enableAutoCleanup': '启用自动清理',
    'keyboard.cleanupDays': '清理天数',
    'keyboard.adminChatId': '管理员会话ID',
    
    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.confirm': '确认',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.add': '添加',
    'common.search': '搜索',
    'common.noData': '暂无数据',
    'common.copy': '复制',
    'common.copied': '已复制',
    'common.refresh': '刷新',
    'common.close': '关闭',
    'common.submit': '提交',
    'common.reset': '重置',
    'common.clear': '清空',
    'common.select': '选择',
    'common.upload': '上传',
    'common.download': '下载',
    'common.preview': '预览',
    'common.test': '测试',
    'common.enable': '启用',
    'common.disable': '禁用',
    'common.enabled': '已启用',
    'common.disabled': '已禁用',
    'common.status': '状态',
    'common.actions': '操作',
    'common.name': '名称',
    'common.description': '描述',
    'common.price': '价格',
    'common.quantity': '数量',
    'common.total': '总计',
    'common.date': '日期',
    'common.time': '时间',
    'common.type': '类型',
    'common.category': '分类',
    'common.all': '全部',
    'common.none': '无',
    'common.yes': '是',
    'common.no': '否',
    'common.or': '或',
    'common.and': '和',
    'common.required': '必填',
    'common.optional': '可选',
    'common.example': '例如',
    'common.tips': '提示',
    'common.warning': '警告',
    'common.info': '信息',
    'common.version': '版本',
    
    // Gateway Config
    'gateway.title': '网关设置',
    'gateway.blockchain': '区块链监听',
    'gateway.receiveAddress': '收款地址',
    'gateway.tronGridKey': 'TronGrid Key',
    'gateway.hupi': '虎皮椒接口',
    'gateway.wechat': '微信',
    'gateway.alipay': '支付宝',
    'gateway.appId': 'App ID',
    'gateway.secret': 'Secret',
    'gateway.antiCollision': '防撞单算法',
    'gateway.antiCollisionDesc': '自动生成毫级随机尾数',
    'gateway.saveAll': '保存所有配置',
    'gateway.saved': '保存成功',
    'gateway.settingsSaved': '设置已保存',
    
    // Product Management
    'product.title': '商品管理',
    'product.add': '添加商品',
    'product.edit': '编辑商品',
    'product.name': '商品名称',
    'product.price': '价格',
    'product.priceCny': '人民币价格',
    'product.priceUsdt': 'USDT价格',
    'product.priceTrx': 'TRX价格',
    'product.stock': '库存',
    'product.duration': '时长',
    'product.active': '上架',
    'product.inactive': '下架',
    'product.tags': '标签',
    'product.refreshRates': '刷新汇率',
    'product.currentRate': '当前汇率',
    
    // Order
    'order.title': '订单管理',
    'order.no': '订单号',
    'order.status': '订单状态',
    'order.pending': '待支付',
    'order.paid': '已支付',
    'order.completed': '已完成',
    'order.cancelled': '已取消',
    'order.expired': '已过期',
    'order.amount': '订单金额',
    'order.payMethod': '支付方式',
    'order.createTime': '创建时间',
    'order.payTime': '支付时间',
    'order.deliverTime': '发货时间',
    
    // TG Shop
    'tgshop.title': 'TG商城',
    'tgshop.products': '商品管理',
    'tgshop.orders': '订单管理',
    'tgshop.categories': '分类管理',
    'tgshop.settings': '商城设置',
    'tgshop.welcome': '欢迎语',
    'tgshop.payment': '支付设置',
    'tgshop.delivery': '发货设置',
    
    // Index/Chat Page
    'chat.welcome': '欢迎使用 TG 机器人管理平台',
    'chat.addBotHint': '点击左侧"添加机器人"按钮开始试用',
    'chat.console': '控制台',
    'chat.online': '在线',
    'chat.offline': '离线',
    'chat.selectChat': '请从左侧选择一个聊天对话',
    'chat.waitMessage': '或等待用户发送消息',
    'chat.inputPlaceholder': '输入回复消息...（可粘贴图片）',
    'chat.send': '发送',
    'chat.trialUsedUp': '试用次数已用完，请绑定激活码继续使用',
    'chat.serviceExpired': '服务已过期，请联系管理员续期',
    'chat.serviceStopped': '服务已停止，无法发送消息',
    'chat.needAuth': '需要购买授权',
    'chat.trialExceeded': '您已使用完',
    'chat.freeMessages': '条免费试用消息。',
    'chat.contactAdmin': '如需继续使用，请联系管理员获取激活码授权。',
    'chat.bindCodeToContinue': '绑定激活码后即可继续使用机器人服务。',
    'chat.later': '稍后再说',
    'chat.goBindCode': '去绑定激活码',
    'chat.admin': '管理员',
    'chat.imagePreview': '放大预览',
    'chat.imageMessage': '图片消息',
    'chat.imageSizeLimit': '图片大小不能超过5MB',
    'chat.preview': '预览',
    'chat.soundOn': '提示音已开启',
    'chat.soundOff': '提示音已关闭',
    'chat.qqSound': 'QQ音',
    'chat.dingSound': '叮咚',
    'chat.bellSound': '铃铛',
    
    // ChatSidebar
    'sidebar.addBot': '添加机器人',
    'sidebar.resetBinding': '重置绑定',
    'sidebar.myBots': '我的机器人',
    'sidebar.noBots': '暂无机器人，点击上方按钮添加',
    'sidebar.trial': '试用',
    'sidebar.expired': '过期',
    'sidebar.validity': '有效期',
    'sidebar.trialUsage': '试用',
    'sidebar.renew': '续期',
    'sidebar.enterCode': '输入激活码',
    'sidebar.bind': '绑定',
    'sidebar.cancel': '取消',
    'sidebar.renewActivate': '续期激活',
    'sidebar.bindCode': '绑定激活码',
    'sidebar.chatList': '聊天对话',
    'sidebar.waitUserMessage': '等待用户发送消息...',
    'sidebar.selectBotFirst': '请先选择一个机器人',
    'sidebar.resetSuccess': '重置成功',
    'sidebar.webhookReset': '机器人Webhook已重新绑定到本系统',
    'sidebar.resetFailed': '重置失败',
    'sidebar.error': '错误',
    'sidebar.enterCodeError': '请输入激活码',
    'sidebar.bindSuccess': '绑定成功',
    'sidebar.codeBindSuccess': '激活码已成功绑定，机器人已激活',
    'sidebar.bindFailed': '绑定失败',
    
    // Console Page
    'console.title': 'Telegram 机器人控制台',
    'console.running': '在线运行中',
    'console.stopped': '已停止',
    'console.loading': '正在加载...',
    'console.accessDenied': '访问被拒绝',
    'console.botUnavailable': '此机器人服务不可用',
    'console.goHome': '返回首页',
    'console.notFound': '未找到',
    'console.activationNotExist': '激活不存在',
    'console.serviceStopped': '服务已停止',
    'console.botStopped': '此机器人服务已被停用',
    'console.serviceExpired': '服务已过期',
    'console.contactAdminRenew': '请联系管理员续期',
    'console.loadFailed': '加载失败',
    'console.cannotGetActivation': '无法获取激活信息',
    'console.sound': '提示音',
    'console.on': '开',
    'console.off': '关',
    'console.selectChatTarget': '选择聊天对象',
    'console.noChat': '暂无聊天记录，等待用户发送消息...',
    'console.selectChatHint': '请选择一个聊天对象',
    'console.inputReply': '输入回复消息...',
    'console.sending': '发送中...',
    'console.sendSuccess': '发送成功',
    'console.messageSent': '消息已发送',
    'console.sendFailed': '发送失败',
    'console.selectChatAndInput': '请选择聊天并输入消息',
    'console.trialLimitTitle': '试用次数已用完',
    'console.trialLimitDesc': '条免费试用消息。如需继续使用，请联系管理员开通完整服务。',
    'console.gotIt': '我知道了',
    'console.telegramAppTip': '📱 在 Telegram APP 中回复',
    'console.telegramAppDesc': '收到转发消息后，直接使用 Telegram 的"回复"功能（长按消息→回复）即可精准回复对应用户。机器人7x24小时在线，即使关闭此网页也能正常工作。',
    
    // Index Page Footer
    'index.aboutTitle': '关于机器人-激活授权联系QQ：3075554556',
    'index.aboutDesc': '我们的TG机器人管理平台让您能够轻松管理与用户的对话。支持自动问候、实时消息转发、多机器人同时管理等功能。无论您是个人用户还是企业，都能找到适合您的解决方案。账号就算被限制只要能创建机器人即可用机器人来实现双向聊天充当客服！网页端不用魔法上网也可以在线接收消息跟回复消息！',
    'index.featuresTitle': '功能特点',
    'index.feature1': '✓ 20条免费试用消息',
    'index.feature2': '✓ 实时消息通知提醒',
    'index.feature3': '✓ 多机器人统一管理',
    'index.feature4': '✓ 简洁易用的操作界面',
    'index.feature5': '✓ 支持自定义问候语',
    'index.feature6': '✓ 支持图片收发',
    
    // Activate Page
    'activate.title': '激活机器人服务',
    'activate.desc': '请输入您的机器人令牌以完成激活',
    'activate.code': '激活码',
    'activate.token': '机器人令牌 (Bot Token)',
    'activate.tokenPlaceholder': '输入您的机器人令牌...',
    'activate.tokenHint': '从 @BotFather 获取的令牌',
    'activate.submit': '激活',
    'activate.activating': '激活中...',
    'activate.success': '激活成功！',
    'activate.successDesc': '机器人已成功激活，即将跳转到控制台',
    'activate.failed': '激活失败',
    'activate.checkToken': '请检查令牌是否正确',
    'activate.error': '错误',
    'activate.enterToken': '请输入机器人令牌',
    'activate.guideTitle': '激活说明',
    'activate.guide1': '• 激活后，机器人将24小时在线运行',
    'activate.guide2': '• 新用户可免费试用20条消息',
    'activate.guide3': '• 试用结束后需联系管理员开通完整服务',
    
    // Config Guide
    'guide.title': '配置说明',
    'guide.all': '全部',
    'guide.noArticles': '该分类下暂无文章',
    
    // KeyboardMenu Page - Sidebar
    'km.sidebar.title': '菜单键盘',
    'km.sidebar.idConnect': 'ID连接&重置',
    'km.sidebar.commandMgmt': '菜单命令管理',
    'km.sidebar.keyboardConfig': '底部键盘配置',
    'km.sidebar.messagePush': '消息推送编辑器',
    'km.sidebar.userData': '用户数据',
    'km.sidebar.tgShop': 'TG商城',
    'km.sidebar.configGuide': '配置说明',
    
    // KeyboardMenu - Settings Panel
    'km.settings.title': 'ID连接&重置',
    'km.settings.desc': 'Token 已自动保存。配置安全监听与 Webhook 状态。',
    'km.settings.connectSettings': '连接设置',
    'km.settings.botId': 'BOT机器人ID',
    'km.settings.userId': '用户ID',
    'km.settings.userIdReceive': '用户 ID【接收用户活动记录如发送指令&关键词】',
    'km.settings.proxyMode': 'Web 代理模式 (CORS Proxy)',
    'km.settings.verifyConnect': '验证并连接',
    'km.settings.disconnect': '断开连接',
    'km.settings.activationCode': '激活码',
    'km.settings.bind': '绑定',
    'km.settings.cloudSync': '同步到云端',
    'km.settings.syncing': '同步中...',
    'km.settings.synced': '已同步到云端',
    'km.settings.syncFailed': '同步失败，点击重试',
    'km.settings.activityLog': '用户活动记录',
    'km.settings.activityLogDesc': '接收用户发送指令/关键词活动',
    'km.settings.bilingualBtn': '双语按钮显示',
    'km.settings.bilingualBtnDesc': '需在底部键盘配置中填写英文',
    'km.settings.exportConfig': '导出配置',
    'km.settings.importConfig': '导入配置',
    'km.settings.deepReset': '深度重置：清理所有用户界面',
    'km.settings.deepResetting': '正在执行深度重置...',
    'km.settings.deepResetSuccess': 'UI 清理完成！已通知用户移除键盘。',
    'km.settings.deepResetFailed': '深度重置失败',
    'km.settings.configSynced': '配置已同步到云端，关闭网页后菜单键盘仍可运行',
    'km.settings.configLoaded': '已从云端加载配置',
    'km.settings.configExported': '配置已导出',
    'km.settings.configImported': '配置导入成功',
    'km.settings.configImportError': '配置文件格式错误',
    'km.settings.connectFirst': '请先连接机器人',
    'km.settings.testSendSuccess': '发送成功！',
    'km.settings.testSendFailed': '发送失败',
    'km.settings.inputTargetId': '请先输入目标 ID',
    'km.settings.trialExpired': '菜单键盘试用已过期，请激活续费后继续使用',
    'km.settings.enterCode': '请输入激活码',
    'km.settings.connected': '已连接',
    'km.settings.connectFailed': '连接失败',
    'km.settings.disconnected': '已断开连接并清除本地缓存',
    'km.settings.networkFailed': '网络请求失败 (CORS)。请确保已开启代理模式或检查网络。',
    
    // KeyboardMenu - Activation Code Binder
    'km.activation.valid': '✅ 菜单键盘有效期至',
    'km.activation.days': '天',
    'km.activation.trial': '⏳ 菜单键盘试用剩余',
    'km.activation.hours': '小时',
    'km.activation.minutes': '分钟',
    'km.activation.expired': '❌ 菜单键盘试用已过期，请激活',
    'km.activation.keyboardExpired': '❌ 菜单键盘已过期，请激活',
    'km.activation.firstUse': '💡 首次使用可试用24小时',
    'km.activation.chatExpire': '双向聊天',
    'km.activation.keyboardExpire': '菜单键盘',
    'km.activation.success': '激活成功',
    'km.activation.bindFailed': '绑定失败',
    
    // KeyboardMenu - Keyboard Editor
    'km.keyboard.title': '多级菜单配置',
    'km.keyboard.desc': '创建多个菜单页，通过"跳转"按钮链接它们。',
    'km.keyboard.newPage': '新建菜单页',
    'km.keyboard.newPageName': '新页面',
    'km.keyboard.newButton': '新按钮',
    'km.keyboard.btnTextCn': '中文按钮文字',
    'km.keyboard.btnTextEn': 'English (可选)',
    'km.keyboard.sendText': '💬 发送文本',
    'km.keyboard.navigateMenu': '📂 跳转菜单',
    'km.keyboard.selectTarget': '选择目标页...',
    'km.keyboard.addNewRow': '添加新行',
    'km.keyboard.pushCurrent': '推送给当前 ID',
    'km.keyboard.broadcastUpdate': '群发更新',
    'km.keyboard.pushing': '推送中...',
    'km.keyboard.menuUpdate': '🔄 菜单更新',
    'km.keyboard.pushSuccess': '已推送页面',
    'km.keyboard.pushFailed': '推送失败',
    'km.keyboard.broadcastStart': '开始向用户推送底部键盘...',
    'km.keyboard.broadcastComplete': '群发完成',
    'km.keyboard.success': '成功',
    'km.keyboard.noUsers': '暂无用户数据，请先让用户发送消息给机器人',
    'km.keyboard.connectAndConfigUserId': '请先连接机器人并配置 User ID',
    'km.keyboard.menuPageName': '菜单页名称',
    'km.keyboard.mainMenu': '主菜单 (Main)',
    'km.keyboard.productList': '产品列表 (Sub)',
    
    // KeyboardMenu - Commands Editor
    'km.commands.title': '菜单命令管理',
    'km.commands.menuBtnConfig': '左下角菜单按钮配置',
    'km.commands.showCommandList': '显示指令列表 (默认)',
    'km.commands.openWebApp': '打开 Web App',
    'km.commands.btnText': '按钮文字',
    'km.commands.webAppUrl': 'Web App URL',
    'km.commands.commandList': '指令列表',
    'km.commands.newCmd': 'new_cmd',
    'km.commands.description': 'description',
    'km.commands.syncToTelegram': '同步至 Telegram',
    'km.commands.saveWebApp': '保存 Web App 配置',
    'km.commands.saving': '保存中...',
    'km.commands.menuSyncSuccess': '菜单按钮 & 指令已同步！',
    'km.commands.menuConfigCleared': '菜单按钮配置已清除！',
    
    // KeyboardMenu - Message Flow Editor
    'km.message.title': '消息推送编辑器',
    'km.message.desc': '编辑消息并保存为自动回复规则',
    'km.message.newMessage': '新增消息',
    'km.message.message': '消息',
    'km.message.triggerLabel': '/start 或 关键词',
    'km.message.textMsg': '📝 文本消息',
    'km.message.photoMsg': '🖼️ 图片消息',
    'km.message.videoMsg': '🎥 视频消息',
    'km.message.disableLinkPreview': '禁用链接预览',
    'km.message.photoUrl': '图片 URL',
    'km.message.videoUrl': '视频 URL (mp4)',
    'km.message.content': '消息内容 (支持 HTML)',
    'km.message.link': '链接',
    'km.message.copy': '复制',
    'km.message.emoji': '表情',
    'km.message.linkText': '链接文字',
    'km.message.linkUrl': '链接地址 (https://...)',
    'km.message.insert': '插入',
    'km.message.cancel': '取消',
    'km.message.copyableText': '可复制文本',
    'km.message.selectEmoji': '选择表情',
    'km.message.inlineButtons': '内联按钮',
    'km.message.addRow': '添加行',
    'km.message.btnText': '按钮文字',
    'km.message.urlType': '🔗 链接',
    'km.message.callbackType': '⚡ 回调',
    'km.message.webAppType': '🌐 Web App',
    'km.message.value': '值',
    'km.message.saveAsAutoReply': '保存为自动回复',
    'km.message.sendToTarget': '发送至目标',
    'km.message.savedAsAutoReply': '已保存为自动回复',
    'km.message.notConnectedOrEmpty': '未连接或 User ID 为空',
    'km.message.configUserIdFirst': '请先配置 User ID',
    'km.message.sentMessages': '已发送消息',
    'km.message.sendFailed': '发送失败',
    'km.message.btnMissingText': '个按钮缺少按钮文字',
    'km.message.btnMissingUrl': '缺少链接地址',
    'km.message.btnMissingCallback': '缺少回调指令/关键词',
    'km.message.btnMissingWebApp': '缺少 Web App 网址',
    'km.message.urlMustStartWith': '的网址必须以 http:// 或 https:// 开头',
    'km.message.row': '第',
    'km.message.column': '行第',
    'km.message.btn': '个按钮',
    
    // KeyboardMenu - Users Panel
    'km.users.title': '用户数据',
    'km.users.total': '共',
    'km.users.users': '位用户',
    'km.users.realTimeSync': '(实时同步)',
    'km.users.notConnected': '(未连接机器人)',
    'km.users.refresh': '刷新',
    'km.users.clearData': '清空数据',
    'km.users.userList': '用户列表',
    'km.users.userId': 'User ID',
    'km.users.nickname': '昵称 / 用户名',
    'km.users.firstSeen': '首次发现',
    'km.users.lastActive': '最后活跃',
    'km.users.actions': '操作',
    'km.users.loading': '加载中...',
    'km.users.noData': '暂无数据。当用户发送消息给机器人时会自动抓取。',
    'km.users.lock': '锁定',
    'km.users.push': '推送',
    'km.users.locked': '已锁定目标用户',
    'km.users.deleted': '已删除用户 ID',
    'km.users.deleteFailed': '删除失败',
    'km.users.cleared': '已清空用户数据',
    'km.users.clearFailed': '清空失败',
    'km.users.confirmClear': '确定要清空所有用户数据吗？',
    'km.users.connectFirst': '请先连接机器人',
    'km.users.welcomeMenu': '📂 欢迎使用菜单',
    'km.users.pushSuccess': '已向用户推送主菜单',
    'km.users.pushFailed': '推送失败',
    
    // KeyboardMenu - Phone Simulator
    'km.simulator.appPreview': 'App Preview',
    'km.simulator.today': 'Today',
    'km.simulator.message': 'Message',
    
    // KeyboardMenu - Default Text
    'km.default.productList': '产品列表',
    'km.default.contactSupport': '联系客服',
    'km.default.softwareProducts': '软件产品',
    'km.default.hardwareProducts': '硬件产品',
    'km.default.back': '🔙 返回上级',
    'km.default.start': '开始使用',
    'km.default.help': '获取帮助',
    'km.default.systemReady': '系统就绪。',
    'km.default.simulateJump': '(模拟跳转) 切换到菜单',
    
    // KeyboardMenu - Toast Messages
    'km.toast.webhookBackupSuccess': '已备份原 Webhook 并开启监听',
    'km.toast.safeListenOn': '安全监听已开启',
    'km.toast.safeListenOnWithBackup': '安全监听已开启 (已加载历史备份)',
    'km.toast.startFailed': '开启失败',
    'km.toast.webhookRestored': '已自动恢复 Webhook 连接',
    'km.toast.webhookRestoreFailed': '恢复 Webhook 失败',
    'km.toast.listenClosed': '监听已关闭。',
    'km.toast.backupRestored': '已从备份恢复 Webhook',
    'km.toast.restoreFailed': '恢复失败',
    
    // KeyboardMenu - Activity Log
    'km.activity.userCapture': '🔔 <b>用户活动捕获</b>',
    'km.activity.user': '👤 用户',
    'km.activity.content': '💬 内容',
    'km.activity.autoProcessed': '✅ 已自动处理',
    'km.activity.noMatchRule': '⚠️ 未匹配规则',
    'km.activity.startChat': '💬 发起私聊',
  },
  en: {
    // Navbar
    'nav.brand': 'Bot Manager',
    'nav.chat': 'Two-way Chat',
    'nav.chat.short': 'Chat',
    'nav.keyboard': 'Menu Keyboard',
    'nav.keyboard.short': 'Menu',
    'nav.store': 'Store',
    'nav.store.short': 'Store',
    'nav.userCenter': 'Account',
    'nav.logout': 'Logout',
    'nav.register': 'Sign Up',
    'nav.login': 'Login',
    
    // Store Page
    'store.title': 'Self-service Store',
    'store.auto': 'Auto Recharge',
    'store.card': 'Card Key',
    'store.selectProduct': 'Select a product',
    'store.selectPayment': 'Select payment method',
    'store.stock': 'Stock',
    'store.soldOut': 'Sold Out',
    'store.days': 'days',
    'store.buy': 'Buy',
    'store.enterBotId': 'Enter your account ID',
    'store.enterContact': 'Enter email or phone',
    'store.payment': 'Payment',
    'store.payNow': 'Pay Now',
    'store.orderQuery': 'Order Query',
    'store.paySuccess': 'Payment Success',
    'store.expired': 'Expired',
    'store.confirmPayment': 'Confirm Payment',
    'store.payAmount': 'Please pay exact amount',
    'store.scanToPay': 'Scan to Pay',
    'store.wechatScan': 'Scan with WeChat to pay',
    'store.alipayScan': 'Scan with Alipay to pay',
    'store.openAlipay': 'Tap to open Alipay',
    'store.paidDone': 'I have paid',
    'store.orderComplete': 'Order Complete',
    'store.cardInfo': 'Card Key',
    'store.copy': 'Copy',
    'store.copySuccess': 'Copied',
    'store.copyFailed': 'Copy failed, please copy manually',
    'store.loadingCard': 'Fetching card key securely...',
    'store.retry': 'Retry',
    'store.noStock': 'Out of stock',
    'store.createOrderFailed': 'Failed to create order, please try again',
    'store.getPayLinkFailed': 'Failed to get payment link, please try again',
    'store.chat': 'Two-way Chat',
    'store.keyboardMenu': 'Menu Keyboard',
    'store.tgMall': 'TG Store',
    'store.connectedGateway': 'Connected to payment gateway...',
    'store.paymentNetwork': 'Current payment network: TRX/TRC20',
    'store.gettingPayLink': 'Getting payment link...',
    'store.addressCopied': 'Address copied',
    'store.queryOrderHint': 'Please enter email or phone to query order!',
    'store.fillContactHint': 'Please fill in email or phone for order inquiry!',
    'store.selectProductFirst': 'Please select a product first',
    'store.selectPaymentMethod': 'Please select payment method',
    'store.enterAccountId': 'Please enter account ID',
    'store.paymentNotDetected': 'Payment not detected. Please ensure payment is complete and try again.',
    'store.queryFailed': 'Failed to query order, please try again',
    'store.deliveryFailed': 'Delivery failed, please retry or check order history',
    'store.cardSoldOut': 'Card key sold out, please contact support',
    'store.systemError': 'System error, please contact support',
    'store.cannotGetProduct': 'Cannot get product info, please contact support',
    'store.anonymous': 'Anonymous',
    'store.none': 'None',
    'store.orderHistory': 'Order History',
    'store.noOrders': 'No orders yet',
    'store.pending': 'Pending',
    'store.paid': 'Paid',
    'store.activationSuccess': 'Activated',
    'store.processing': 'Processing...',
    'store.activationFailed': 'Activation failed',
    'store.contact': 'Contact',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.submit': 'Submit',
    'auth.welcomeBack': 'Welcome back!',
    'auth.createAccount': 'Create Account',
    'auth.loginDesc': 'Please login to your account',
    'auth.registerDesc': 'Please fill in the information to register',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.forgotPassword': 'Forgot password?',
    'auth.loginSuccess': 'Login successful',
    'auth.registerSuccess': 'Registration successful',
    'auth.autoLogin': 'Auto logged in, start using now!',
    'auth.loginFailed': 'Login failed',
    'auth.registerFailed': 'Registration failed',
    'auth.invalidCredentials': 'Invalid email or password',
    'auth.emailRegistered': 'This email is already registered',
    'auth.passwordMin': 'Password must be at least 6 characters',
    'auth.fillEmailPassword': 'Please fill in email and password',
    'auth.enterPassword': 'Enter password',
    'auth.minChars': 'At least 6 characters',
    'auth.noRegisterTip': 'You can try bot features on homepage without registration',
    'auth.logging': 'Logging in...',
    'auth.registering': 'Registering...',
    
    // User Center
    'user.center': 'User Center',
    'user.profile': 'Profile',
    'user.settings': 'Settings',
    'user.bots': 'My Bots',
    'user.orders': 'My Orders',
    'user.balance': 'Balance',
    'user.recharge': 'Recharge',
    'user.addBot': 'Add Bot',
    'user.noBot': 'No bots yet',
    'user.addFirstBot': 'Click above to add your first bot',
    'user.token': 'Token',
    'user.validity': 'Validity',
    'user.forever': 'Forever',
    'user.expired': 'Expired',
    'user.trial': 'Trial',
    'user.trialFull': 'Trial limit reached',
    'user.activated': 'Activated',
    'user.trialing': 'Trial',
    'user.renew': 'Renew',
    'user.serviceExpired': 'Service expired, please contact admin to renew',
    'user.trialUsedUp': 'Trial quota used up, please bind activation code',
    'user.bindCode': 'Bind Activation Code',
    'user.renewActivate': 'Renew Activation',
    'user.enterCode': 'Enter activation code...',
    'user.binding': 'Binding...',
    'user.bind': 'Bind',
    'user.deleteSuccess': 'Deleted',
    'user.botRemoved': 'Bot removed from list',
    'user.deleteFailed': 'Delete failed',
    'user.bindSuccess': 'Binding successful',
    'user.codeBindSuccess': 'Activation code bound, bot activated',
    'user.bindFailed': 'Binding failed',
    'user.addSuccess': 'Added',
    'user.canTrial': 'Bot added, free trial available:',
    'user.messages': 'messages',
    'user.loading': 'Loading...',
    'user.webPortClosed': 'Web port closed',
    'user.enterCodeError': 'Please enter activation code',
    
    // Add Bot Dialog
    'bot.addTitle': 'Add Telegram Bot',
    'bot.addDesc': 'Enter bot info to start trial. No registration required. Free 20 messages trial.',
    'bot.token': 'Bot Token',
    'bot.tokenPlaceholder': 'e.g. 123456789:ABCdefGHIjklMNOpqrsTUVwxyz',
    'bot.tokenHint': 'Get token from @BotFather, go to t.me/BotFather',
    'bot.userId': 'Your Telegram User ID',
    'bot.userIdPlaceholder': 'e.g. 123456789',
    'bot.userIdHint': 'Get ID from @userinfobot, go to t.me/userinfobot',
    'bot.greeting': 'Welcome Message',
    'bot.greetingPlaceholder': 'Auto reply when user sends /start',
    'bot.greetingDefault': 'Hello! 👋 How can I help you?',
    'bot.startTrial': 'Start Trial',
    'bot.adding': 'Adding...',
    'bot.addFailed': 'Add failed',
    'bot.checkToken': 'Please check if token is correct',
    'bot.fillRequired': 'Please fill in bot token and user ID',
    
    // Keyboard Menu
    'keyboard.title': 'Menu Keyboard',
    'keyboard.connect': 'Connect Bot',
    'keyboard.disconnect': 'Disconnect',
    'keyboard.connected': 'Connected',
    'keyboard.notConnected': 'Not Connected',
    'keyboard.botToken': 'Bot Token',
    'keyboard.userId': 'User ID',
    'keyboard.settings': 'Settings',
    'keyboard.commands': 'Commands',
    'keyboard.menu': 'Menu Config',
    'keyboard.autoReply': 'Auto Reply',
    'keyboard.flowMessage': 'Flow Messages',
    'keyboard.users': 'User Management',
    'keyboard.shop': 'TG Shop',
    'keyboard.guide': 'Config Guide',
    'keyboard.message': 'Message Push',
    'keyboard.messageEditor': 'Message Editor',
    'keyboard.addMessage': 'Add Message',
    'keyboard.deleteMessage': 'Delete Message',
    'keyboard.messageType': 'Message Type',
    'keyboard.text': 'Text',
    'keyboard.photo': 'Photo',
    'keyboard.video': 'Video',
    'keyboard.content': 'Content',
    'keyboard.mediaUrl': 'Media URL',
    'keyboard.inlineKeyboard': 'Inline Keyboard',
    'keyboard.addButton': 'Add Button',
    'keyboard.addRow': 'Add Row',
    'keyboard.buttonText': 'Button Text',
    'keyboard.buttonType': 'Button Type',
    'keyboard.buttonValue': 'Button Value',
    'keyboard.url': 'URL',
    'keyboard.callback': 'Callback',
    'keyboard.webApp': 'Web App',
    'keyboard.preview': 'Preview',
    'keyboard.send': 'Send',
    'keyboard.save': 'Save',
    'keyboard.syncToCloud': 'Sync to Cloud',
    'keyboard.loadFromCloud': 'Load from Cloud',
    'keyboard.export': 'Export',
    'keyboard.import': 'Import',
    'keyboard.addCommand': 'Add Command',
    'keyboard.commandName': 'Command Name',
    'keyboard.commandDesc': 'Command Description',
    'keyboard.addMenuPage': 'Add Menu Page',
    'keyboard.pageName': 'Page Name',
    'keyboard.addMenuRow': 'Add Menu Row',
    'keyboard.buttonAction': 'Button Action',
    'keyboard.navigate': 'Navigate',
    'keyboard.sendText': 'Send Text',
    'keyboard.targetPage': 'Target Page',
    'keyboard.mainMenu': 'Main Menu',
    'keyboard.subMenu': 'Sub Menu',
    'keyboard.back': 'Back',
    'keyboard.addRule': 'Add Rule',
    'keyboard.triggerType': 'Trigger Type',
    'keyboard.keyword': 'Keyword',
    'keyboard.command': 'Command',
    'keyboard.triggerValue': 'Trigger Value',
    'keyboard.replyMessages': 'Reply Messages',
    'keyboard.disablePreview': 'Disable Link Preview',
    'keyboard.proxyMode': 'Proxy Mode',
    'keyboard.enableProxy': 'Enable Proxy',
    'keyboard.webhookStatus': 'Webhook Status',
    'keyboard.webhookActive': 'Webhook Active',
    'keyboard.webhookInactive': 'Webhook Inactive',
    'keyboard.refreshWebhook': 'Refresh Webhook',
    'keyboard.setWebhook': 'Set Webhook',
    'keyboard.deleteWebhook': 'Delete Webhook',
    'keyboard.botInfo': 'Bot Info',
    'keyboard.botName': 'Bot Name',
    'keyboard.botUsername': 'Bot Username',
    'keyboard.targetChat': 'Target Chat',
    'keyboard.chatId': 'Chat ID',
    'keyboard.selectUser': 'Select User',
    'keyboard.userList': 'User List',
    'keyboard.noUsers': 'No users',
    'keyboard.lastSeen': 'Last seen',
    'keyboard.joined': 'Joined',
    'keyboard.total': 'Total',
    'keyboard.users.count': 'users',
    'keyboard.bilingualButton': 'Bilingual Button',
    'keyboard.enableBilingual': 'Enable Bilingual Buttons',
    'keyboard.englishText': 'English Text',
    'keyboard.forceMenuOnStart': 'Force Menu on Start',
    'keyboard.activityLog': 'Activity Log',
    'keyboard.enableActivityLog': 'Enable Activity Log',
    'keyboard.autoCleanup': 'Auto Cleanup',
    'keyboard.enableAutoCleanup': 'Enable Auto Cleanup',
    'keyboard.cleanupDays': 'Cleanup Days',
    'keyboard.adminChatId': 'Admin Chat ID',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.noData': 'No data',
    'common.copy': 'Copy',
    'common.copied': 'Copied',
    'common.refresh': 'Refresh',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.select': 'Select',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.preview': 'Preview',
    'common.test': 'Test',
    'common.enable': 'Enable',
    'common.disable': 'Disable',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.type': 'Type',
    'common.category': 'Category',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.or': 'or',
    'common.and': 'and',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.example': 'e.g.',
    'common.tips': 'Tips',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.version': 'Version',
    
    // Gateway Config
    'gateway.title': 'Gateway Settings',
    'gateway.blockchain': 'Blockchain Monitor',
    'gateway.receiveAddress': 'Receive Address',
    'gateway.tronGridKey': 'TronGrid Key',
    'gateway.hupi': 'Hupi Payment',
    'gateway.wechat': 'WeChat',
    'gateway.alipay': 'Alipay',
    'gateway.appId': 'App ID',
    'gateway.secret': 'Secret',
    'gateway.antiCollision': 'Anti-Collision Algorithm',
    'gateway.antiCollisionDesc': 'Auto generate random decimals',
    'gateway.saveAll': 'Save All Settings',
    'gateway.saved': 'Saved',
    'gateway.settingsSaved': 'Settings saved',
    
    // Product Management
    'product.title': 'Product Management',
    'product.add': 'Add Product',
    'product.edit': 'Edit Product',
    'product.name': 'Product Name',
    'product.price': 'Price',
    'product.priceCny': 'CNY Price',
    'product.priceUsdt': 'USDT Price',
    'product.priceTrx': 'TRX Price',
    'product.stock': 'Stock',
    'product.duration': 'Duration',
    'product.active': 'Active',
    'product.inactive': 'Inactive',
    'product.tags': 'Tags',
    'product.refreshRates': 'Refresh Rates',
    'product.currentRate': 'Current Rate',
    
    // Order
    'order.title': 'Order Management',
    'order.no': 'Order No.',
    'order.status': 'Order Status',
    'order.pending': 'Pending',
    'order.paid': 'Paid',
    'order.completed': 'Completed',
    'order.cancelled': 'Cancelled',
    'order.expired': 'Expired',
    'order.amount': 'Amount',
    'order.payMethod': 'Payment Method',
    'order.createTime': 'Created At',
    'order.payTime': 'Paid At',
    'order.deliverTime': 'Delivered At',
    
    // TG Shop
    'tgshop.title': 'TG Shop',
    'tgshop.products': 'Products',
    'tgshop.orders': 'Orders',
    'tgshop.categories': 'Categories',
    'tgshop.settings': 'Shop Settings',
    'tgshop.welcome': 'Welcome Message',
    'tgshop.payment': 'Payment Settings',
    'tgshop.delivery': 'Delivery Settings',
    
    // Index/Chat Page
    'chat.welcome': 'Welcome to TG Bot Management Platform',
    'chat.addBotHint': 'Click "Add Bot" button on the left to start',
    'chat.console': 'Console',
    'chat.online': 'Online',
    'chat.offline': 'Offline',
    'chat.selectChat': 'Please select a chat from the left',
    'chat.waitMessage': 'Or wait for user messages',
    'chat.inputPlaceholder': 'Enter reply message... (paste image supported)',
    'chat.send': 'Send',
    'chat.trialUsedUp': 'Trial quota used up, please bind activation code to continue',
    'chat.serviceExpired': 'Service expired, please contact admin to renew',
    'chat.serviceStopped': 'Service stopped, cannot send messages',
    'chat.needAuth': 'Authorization Required',
    'chat.trialExceeded': 'You have used up',
    'chat.freeMessages': 'free trial messages.',
    'chat.contactAdmin': 'To continue, please contact admin for activation code.',
    'chat.bindCodeToContinue': 'Bind activation code to continue using the bot service.',
    'chat.later': 'Maybe Later',
    'chat.goBindCode': 'Bind Activation Code',
    'chat.admin': 'Admin',
    'chat.imagePreview': 'Image Preview',
    'chat.imageMessage': 'Image Message',
    'chat.imageSizeLimit': 'Image size cannot exceed 5MB',
    'chat.preview': 'Preview',
    'chat.soundOn': 'Sound On',
    'chat.soundOff': 'Sound Off',
    'chat.qqSound': 'QQ Sound',
    'chat.dingSound': 'Ding',
    'chat.bellSound': 'Bell',
    
    // ChatSidebar
    'sidebar.addBot': 'Add Bot',
    'sidebar.resetBinding': 'Reset Binding',
    'sidebar.myBots': 'My Bots',
    'sidebar.noBots': 'No bots yet, click above to add',
    'sidebar.trial': 'Trial',
    'sidebar.expired': 'Expired',
    'sidebar.validity': 'Validity',
    'sidebar.trialUsage': 'Trial',
    'sidebar.renew': 'Renew',
    'sidebar.enterCode': 'Enter activation code',
    'sidebar.bind': 'Bind',
    'sidebar.cancel': 'Cancel',
    'sidebar.renewActivate': 'Renew Activation',
    'sidebar.bindCode': 'Bind Activation Code',
    'sidebar.chatList': 'Chat List',
    'sidebar.waitUserMessage': 'Waiting for user messages...',
    'sidebar.selectBotFirst': 'Please select a bot first',
    'sidebar.resetSuccess': 'Reset successful',
    'sidebar.webhookReset': 'Bot webhook has been reset to this system',
    'sidebar.resetFailed': 'Reset failed',
    'sidebar.error': 'Error',
    'sidebar.enterCodeError': 'Please enter activation code',
    'sidebar.bindSuccess': 'Binding successful',
    'sidebar.codeBindSuccess': 'Activation code bound, bot activated',
    'sidebar.bindFailed': 'Binding failed',
    
    // Console Page
    'console.title': 'Telegram Bot Console',
    'console.running': 'Running',
    'console.stopped': 'Stopped',
    'console.loading': 'Loading...',
    'console.accessDenied': 'Access Denied',
    'console.botUnavailable': 'This bot service is unavailable',
    'console.goHome': 'Go Home',
    'console.notFound': 'Not Found',
    'console.activationNotExist': 'Activation does not exist',
    'console.serviceStopped': 'Service stopped',
    'console.botStopped': 'This bot service has been disabled',
    'console.serviceExpired': 'Service expired',
    'console.contactAdminRenew': 'Please contact admin to renew',
    'console.loadFailed': 'Load failed',
    'console.cannotGetActivation': 'Cannot get activation info',
    'console.sound': 'Sound',
    'console.on': 'On',
    'console.off': 'Off',
    'console.selectChatTarget': 'Select chat target',
    'console.noChat': 'No chat history, waiting for user messages...',
    'console.selectChatHint': 'Please select a chat target',
    'console.inputReply': 'Enter reply message...',
    'console.sending': 'Sending...',
    'console.sendSuccess': 'Sent successfully',
    'console.messageSent': 'Message sent',
    'console.sendFailed': 'Send failed',
    'console.selectChatAndInput': 'Please select chat and enter message',
    'console.trialLimitTitle': 'Trial Limit Reached',
    'console.trialLimitDesc': 'free trial messages. To continue, please contact admin for full service.',
    'console.gotIt': 'Got it',
    'console.telegramAppTip': '📱 Reply in Telegram App',
    'console.telegramAppDesc': 'After receiving forwarded messages, use Telegram\'s "Reply" feature (long press message → Reply) to reply to specific users. The bot is online 24/7, works even when this page is closed.',
    
    // Index Page Footer
    'index.aboutTitle': 'About Bot - Contact QQ: 3075554556 for Activation',
    'index.aboutDesc': 'Our TG bot management platform lets you easily manage conversations with users. Supports auto greetings, real-time message forwarding, multi-bot management, and more. Whether personal or business use, we have the solution for you. Even if your account is restricted, you can use bots for two-way chat as customer service! Web client works without VPN!',
    'index.featuresTitle': 'Features',
    'index.feature1': '✓ 20 free trial messages',
    'index.feature2': '✓ Real-time message notifications',
    'index.feature3': '✓ Multi-bot unified management',
    'index.feature4': '✓ Simple and intuitive interface',
    'index.feature5': '✓ Custom welcome messages',
    'index.feature6': '✓ Image sending/receiving support',
    
    // Activate Page
    'activate.title': 'Activate Bot Service',
    'activate.desc': 'Enter your bot token to complete activation',
    'activate.code': 'Activation Code',
    'activate.token': 'Bot Token',
    'activate.tokenPlaceholder': 'Enter your bot token...',
    'activate.tokenHint': 'Token from @BotFather',
    'activate.submit': 'Activate',
    'activate.activating': 'Activating...',
    'activate.success': 'Activation Successful!',
    'activate.successDesc': 'Bot activated successfully, redirecting to console',
    'activate.failed': 'Activation Failed',
    'activate.checkToken': 'Please check if token is correct',
    'activate.error': 'Error',
    'activate.enterToken': 'Please enter bot token',
    'activate.guideTitle': 'Activation Guide',
    'activate.guide1': '• After activation, bot runs 24/7',
    'activate.guide2': '• New users get 20 free trial messages',
    'activate.guide3': '• Contact admin after trial for full service',
    
    // Config Guide
    'guide.title': 'Configuration Guide',
    'guide.all': 'All',
    'guide.noArticles': 'No articles in this category',
    
    // KeyboardMenu Page - Sidebar
    'km.sidebar.title': 'Menu Keyboard',
    'km.sidebar.idConnect': 'ID Connect & Reset',
    'km.sidebar.commandMgmt': 'Command Management',
    'km.sidebar.keyboardConfig': 'Keyboard Config',
    'km.sidebar.messagePush': 'Message Push Editor',
    'km.sidebar.userData': 'User Data',
    'km.sidebar.tgShop': 'TG Shop',
    'km.sidebar.configGuide': 'Config Guide',
    
    // KeyboardMenu - Settings Panel
    'km.settings.title': 'ID Connect & Reset',
    'km.settings.desc': 'Token auto-saved. Configure safe monitoring and Webhook status.',
    'km.settings.connectSettings': 'Connection Settings',
    'km.settings.botId': 'BOT Token ID',
    'km.settings.userId': 'User ID',
    'km.settings.userIdReceive': 'User ID (Receive user activity logs such as commands & keywords)',
    'km.settings.proxyMode': 'Web Proxy Mode (CORS Proxy)',
    'km.settings.verifyConnect': 'Verify & Connect',
    'km.settings.disconnect': 'Disconnect',
    'km.settings.activationCode': 'Activation Code',
    'km.settings.bind': 'Bind',
    'km.settings.cloudSync': 'Sync to Cloud',
    'km.settings.syncing': 'Syncing...',
    'km.settings.synced': 'Synced to Cloud',
    'km.settings.syncFailed': 'Sync failed, click to retry',
    'km.settings.activityLog': 'User Activity Log',
    'km.settings.activityLogDesc': 'Receive user commands/keywords activity',
    'km.settings.bilingualBtn': 'Bilingual Button Display',
    'km.settings.bilingualBtnDesc': 'Fill in English in keyboard config',
    'km.settings.exportConfig': 'Export Config',
    'km.settings.importConfig': 'Import Config',
    'km.settings.deepReset': 'Deep Reset: Clear All User Interfaces',
    'km.settings.deepResetting': 'Performing deep reset...',
    'km.settings.deepResetSuccess': 'UI cleanup complete! Users notified to remove keyboard.',
    'km.settings.deepResetFailed': 'Deep reset failed',
    'km.settings.configSynced': 'Config synced to cloud, menu keyboard works even after closing page',
    'km.settings.configLoaded': 'Config loaded from cloud',
    'km.settings.configExported': 'Config exported',
    'km.settings.configImported': 'Config imported successfully',
    'km.settings.configImportError': 'Config file format error',
    'km.settings.connectFirst': 'Please connect bot first',
    'km.settings.testSendSuccess': 'Send successful!',
    'km.settings.testSendFailed': 'Send failed',
    'km.settings.inputTargetId': 'Please enter target ID first',
    'km.settings.trialExpired': 'Menu keyboard trial expired, please activate to continue',
    'km.settings.enterCode': 'Please enter activation code',
    'km.settings.connected': 'Connected',
    'km.settings.connectFailed': 'Connection failed',
    'km.settings.disconnected': 'Disconnected and local cache cleared',
    'km.settings.networkFailed': 'Network request failed (CORS). Please enable proxy mode or check network.',
    
    // KeyboardMenu - Activation Code Binder
    'km.activation.valid': '✅ Menu keyboard valid until',
    'km.activation.days': 'days',
    'km.activation.trial': '⏳ Menu keyboard trial remaining',
    'km.activation.hours': 'hours',
    'km.activation.minutes': 'minutes',
    'km.activation.expired': '❌ Menu keyboard trial expired, please activate',
    'km.activation.keyboardExpired': '❌ Menu keyboard expired, please activate',
    'km.activation.firstUse': '💡 First use includes 24-hour trial',
    'km.activation.chatExpire': 'Two-way Chat',
    'km.activation.keyboardExpire': 'Menu Keyboard',
    'km.activation.success': 'Activation successful',
    'km.activation.bindFailed': 'Binding failed',
    
    // KeyboardMenu - Keyboard Editor
    'km.keyboard.title': 'Multi-level Menu Config',
    'km.keyboard.desc': 'Create multiple menu pages and link them with "Navigate" buttons.',
    'km.keyboard.newPage': 'New Menu Page',
    'km.keyboard.newPageName': 'New Page',
    'km.keyboard.newButton': 'New Button',
    'km.keyboard.btnTextCn': 'Chinese Button Text',
    'km.keyboard.btnTextEn': 'English (Optional)',
    'km.keyboard.sendText': '💬 Send Text',
    'km.keyboard.navigateMenu': '📂 Navigate Menu',
    'km.keyboard.selectTarget': 'Select target page...',
    'km.keyboard.addNewRow': 'Add New Row',
    'km.keyboard.pushCurrent': 'Push to Current ID',
    'km.keyboard.broadcastUpdate': 'Broadcast Update',
    'km.keyboard.pushing': 'Pushing...',
    'km.keyboard.menuUpdate': '🔄 Menu Update',
    'km.keyboard.pushSuccess': 'Page pushed',
    'km.keyboard.pushFailed': 'Push failed',
    'km.keyboard.broadcastStart': 'Starting broadcast to users...',
    'km.keyboard.broadcastComplete': 'Broadcast complete',
    'km.keyboard.success': 'success',
    'km.keyboard.noUsers': 'No user data, please have users send messages to bot first',
    'km.keyboard.connectAndConfigUserId': 'Please connect bot and configure User ID first',
    'km.keyboard.menuPageName': 'Menu page name',
    'km.keyboard.mainMenu': 'Main Menu',
    'km.keyboard.productList': 'Product List (Sub)',
    
    // KeyboardMenu - Commands Editor
    'km.commands.title': 'Command Management',
    'km.commands.menuBtnConfig': 'Bottom-left Menu Button Config',
    'km.commands.showCommandList': 'Show Command List (Default)',
    'km.commands.openWebApp': 'Open Web App',
    'km.commands.btnText': 'Button Text',
    'km.commands.webAppUrl': 'Web App URL',
    'km.commands.commandList': 'Command List',
    'km.commands.newCmd': 'new_cmd',
    'km.commands.description': 'description',
    'km.commands.syncToTelegram': 'Sync to Telegram',
    'km.commands.saveWebApp': 'Save Web App Config',
    'km.commands.saving': 'Saving...',
    'km.commands.menuSyncSuccess': 'Menu button & commands synced!',
    'km.commands.menuConfigCleared': 'Menu button config cleared!',
    
    // KeyboardMenu - Message Flow Editor
    'km.message.title': 'Message Push Editor',
    'km.message.desc': 'Edit messages and save as auto-reply rules',
    'km.message.newMessage': 'New Message',
    'km.message.message': 'Message',
    'km.message.triggerLabel': '/start or keyword',
    'km.message.textMsg': '📝 Text Message',
    'km.message.photoMsg': '🖼️ Photo Message',
    'km.message.videoMsg': '🎥 Video Message',
    'km.message.disableLinkPreview': 'Disable Link Preview',
    'km.message.photoUrl': 'Photo URL',
    'km.message.videoUrl': 'Video URL (mp4)',
    'km.message.content': 'Message Content (HTML supported)',
    'km.message.link': 'Link',
    'km.message.copy': 'Copy',
    'km.message.emoji': 'Emoji',
    'km.message.linkText': 'Link Text',
    'km.message.linkUrl': 'Link URL (https://...)',
    'km.message.insert': 'Insert',
    'km.message.cancel': 'Cancel',
    'km.message.copyableText': 'Copyable Text',
    'km.message.selectEmoji': 'Select Emoji',
    'km.message.inlineButtons': 'Inline Buttons',
    'km.message.addRow': 'Add Row',
    'km.message.btnText': 'Button Text',
    'km.message.urlType': '🔗 URL',
    'km.message.callbackType': '⚡ Callback',
    'km.message.webAppType': '🌐 Web App',
    'km.message.value': 'Value',
    'km.message.saveAsAutoReply': 'Save as Auto Reply',
    'km.message.sendToTarget': 'Send to Target',
    'km.message.savedAsAutoReply': 'Saved as auto reply',
    'km.message.notConnectedOrEmpty': 'Not connected or User ID is empty',
    'km.message.configUserIdFirst': 'Please configure User ID first',
    'km.message.sentMessages': 'messages sent',
    'km.message.sendFailed': 'Send failed',
    'km.message.btnMissingText': 'button missing button text',
    'km.message.btnMissingUrl': 'missing URL',
    'km.message.btnMissingCallback': 'missing callback command/keyword',
    'km.message.btnMissingWebApp': 'missing Web App URL',
    'km.message.urlMustStartWith': 'URL must start with http:// or https://',
    'km.message.row': 'Row',
    'km.message.column': 'Column',
    'km.message.btn': 'button',
    
    // KeyboardMenu - Users Panel
    'km.users.title': 'User Data',
    'km.users.total': 'Total',
    'km.users.users': 'users',
    'km.users.realTimeSync': '(Real-time sync)',
    'km.users.notConnected': '(Bot not connected)',
    'km.users.refresh': 'Refresh',
    'km.users.clearData': 'Clear Data',
    'km.users.userList': 'User List',
    'km.users.userId': 'User ID',
    'km.users.nickname': 'Nickname / Username',
    'km.users.firstSeen': 'First Seen',
    'km.users.lastActive': 'Last Active',
    'km.users.actions': 'Actions',
    'km.users.loading': 'Loading...',
    'km.users.noData': 'No data. Users will be captured when they message the bot.',
    'km.users.lock': 'Lock',
    'km.users.push': 'Push',
    'km.users.locked': 'Locked target user',
    'km.users.deleted': 'Deleted user ID',
    'km.users.deleteFailed': 'Delete failed',
    'km.users.cleared': 'User data cleared',
    'km.users.clearFailed': 'Clear failed',
    'km.users.confirmClear': 'Are you sure to clear all user data?',
    'km.users.connectFirst': 'Please connect bot first',
    'km.users.welcomeMenu': '📂 Welcome to Menu',
    'km.users.pushSuccess': 'Main menu pushed to user',
    'km.users.pushFailed': 'Push failed',
    
    // KeyboardMenu - Phone Simulator
    'km.simulator.appPreview': 'App Preview',
    'km.simulator.today': 'Today',
    'km.simulator.message': 'Message',
    
    // KeyboardMenu - Default Text
    'km.default.productList': 'Products',
    'km.default.contactSupport': 'Contact Support',
    'km.default.softwareProducts': 'Software',
    'km.default.hardwareProducts': 'Hardware',
    'km.default.back': '🔙 Back',
    'km.default.start': 'Start',
    'km.default.help': 'Get Help',
    'km.default.systemReady': 'System ready.',
    'km.default.simulateJump': '(Simulate) Navigate to menu',
    
    // KeyboardMenu - Toast Messages
    'km.toast.webhookBackupSuccess': 'Webhook backed up, monitoring started',
    'km.toast.safeListenOn': 'Safe monitoring enabled',
    'km.toast.safeListenOnWithBackup': 'Safe monitoring enabled (with backup)',
    'km.toast.startFailed': 'Start failed',
    'km.toast.webhookRestored': 'Webhook connection restored',
    'km.toast.webhookRestoreFailed': 'Webhook restore failed',
    'km.toast.listenClosed': 'Monitoring closed.',
    'km.toast.backupRestored': 'Webhook restored from backup',
    'km.toast.restoreFailed': 'Restore failed',
    
    // KeyboardMenu - Activity Log
    'km.activity.userCapture': '🔔 <b>User Activity Captured</b>',
    'km.activity.user': '👤 User',
    'km.activity.content': '💬 Content',
    'km.activity.autoProcessed': '✅ Auto processed',
    'km.activity.noMatchRule': '⚠️ No matching rule',
    'km.activity.startChat': '💬 Start Chat',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved === 'en' ? 'en' : 'zh') as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default useLanguage;
